export const LOGIN_ACTION = "LOGIN_ACTION";
export const LOGOUT_ACTION = "LOGOUT_ACTION";
export const FETCH_ALL_PRODUCTIONS_ACTION = "FETCH_ALL_PRODUCTIONS_ACTION";
export const FETCH_USER_INFO_ACTION = "FETCH_USER_INFO_ACTION";
export const PUSH_CARTS_TO_SERVER_ACTION = "PUSH_CARTS_TO_SERVER_ACTION";
