export const ADD_CART_ITEM_MUTATION = "ADD_CART_ITEM_MUTATION";
export const DEL_CART_ITEM_MUTATION = "DEL_CART_ITEM_MUTATION";
export const SET_USER_MUTATION = "SET_USER_MUTATION";
export const FETCH_ALL_PRODUCTIONS_MUTATION = "FETCH_ALL_PRODUCTIONS_MUTATION";
export const FETCH_USER_INFO_MUTATION = "FETCH_USER_INFO_MUTATION";
export const CLEAR_CART_ITEM_MUTATION = "CLEAR_CART_ITEM_MUTATION";
export const PUSH_CARTS_TO_SERVER_MUTATION = "PUSH_CARTS_TO_SERVER_MUTATION";