export const ADD_CART_ITEM_MUTATION = 'ADD_CART_ITEM_MUTATION';
export const DEL_CART_ITEM_MUTATION = 'DEL_CART_ITEM_MUTATION';
export const SET_USER_MUTATION = 'SET_USER_MUTATION';
export const FETCH_ALL_PRODUCTIONS_MUTATION = 'FETCH_ALL_PRODUCTIONS_MUTATION';
